// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageNA21.Data;

namespace StorageNA21.Migrations
{
    [DbContext(typeof(StorageNA21Context))]
    [Migration("20210305101930_DataAttribute")]
    partial class DataAttribute
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StorageNA21.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Count = 156,
                            Description = "Stupid",
                            Name = "Iphone",
                            OrderDate = new DateTime(2021, 2, 27, 11, 19, 29, 569, DateTimeKind.Local).AddTicks(5948),
                            Price = 15600,
                            Shelf = "4B"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Count = 98,
                            Description = "Better",
                            Name = "S10",
                            OrderDate = new DateTime(2021, 2, 10, 11, 19, 29, 571, DateTimeKind.Local).AddTicks(5733),
                            Price = 12450,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            Count = 23,
                            Description = "Stupid",
                            Name = "MacBook",
                            OrderDate = new DateTime(2021, 2, 28, 11, 19, 29, 571, DateTimeKind.Local).AddTicks(5766),
                            Price = 45600,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computer",
                            Count = 32,
                            Description = "Stupid",
                            Name = "Suface X",
                            OrderDate = new DateTime(2021, 1, 24, 11, 19, 29, 571, DateTimeKind.Local).AddTicks(5770),
                            Price = 26850,
                            Shelf = "5C"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Office Supplies",
                            Count = 15651,
                            Description = "Stupid",
                            Name = "Pen",
                            OrderDate = new DateTime(2021, 2, 27, 11, 19, 29, 571, DateTimeKind.Local).AddTicks(5773),
                            Price = 1,
                            Shelf = "45W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
